# Generated by Django 5.2.7 on 2025-10-18 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("amazon", "Amazon Pay"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "merchant_request_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("result_code", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "result_desc",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("raw_callback", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
